import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/fonts/Montserrat-Regular.ttf" />
        <link rel="stylesheet" href="/fonts/Montserrat-Medium.ttf" />
        <link rel="stylesheet" href="/fonts/Montserrat-SemiBold.ttf" />
        <link rel="stylesheet" href="/fonts/Montserrat-Light.ttf" />
        <link rel="stylesheet" href="/fonts/Montserrat-LightItalic.ttf" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
